apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-test-1
spec:
  template:
    spec:
      containers:
        - name: template-test-1
          env:
            - name: ENVIRONMENT
              value: dev
